language: go

go:
  - "1.10"

services:
  - docker

before_install:
  # Install dep
  # (from: https://github.com/travis-ci/travis-ci/issues/8301#issuecomment-384963911)
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

# (from: https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139)
# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

script:
  # Just working-test
  - ./working_test.bash

cache:
  - apt