language: go

go:
  - "1.10"

services:
  - docker

before_install:
  # Install dep
  # (from: https://github.com/sue445/zatsu_monitor/blob/c265f1b9301c056cbac5006952270812c9155266/.travis.yml)
  - go get github.com/golang/dep/...

# (from: https://github.com/sue445/zatsu_monitor/blob/c265f1b9301c056cbac5006952270812c9155266/.travis.yml)
install:
  - $GOPATH/bin/dep ensure

script:
  # Just working-test
  - ./working_test.bash

cache:
  - apt