[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "2.0.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.6.3"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "^3.0.1"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  name = "github.com/Code-Hex/pget"
  version = "0.0.6"
